### ISSUE TITLE
Unexpected scale/units of pynufft.adjoint()

### ISSUE THREAD

**Issue by lord-blueberry** [jyhmiinlin/pynufft#14]
Maybe this is just a documentation issue. I want to create an image from non-uniformly sampled Fourier Components. I got it working with pyNFFT. With pynufft, I ran into two issues:

### Issue 1: Pixel Intensity Scale
The reconstructed image looked alright, but all pixel intensities are close to 0. In my case, the pixels should have values ~10'000. Does pynufft automatically normalize the image? 

### Issue 2: Scale of x and y
For the IFT, I guess my trouble is figuring out what units pynufft uses for x and y:
<a href="https://www.codecogs.com/eqnedit.php?latex=f(x,y)&space;=&space;\iint&space;F(u,v)&space;exp(2\pi&space;i&space;(u*x&plus;v*y))&space;du&space;dv&space;\;;&space;(x,y)&space;\in\,&space;???" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f(x,y)&space;=&space;\iint&space;F(u,v)&space;exp(2\pi&space;i&space;(u*x&plus;v*y))&space;du&space;dv&space;\;;&space;(x,y)&space;\in\,&space;???" title="f(x,y) = \iint F(u,v) exp(2\pi i (u*x+v*y)) du dv \;; (x,y) \in\, ???" /></a>

If my image is of size (N, N), I expect the behaviour of pyNFFT: x and y run from -(N/2) up to and including (N/2)-1. What does pynufft do?

Below is a minimal example of my confusion. I expect img == img2, but

- maximum of img is 5.5, while the maximum of img2 is << 1
- img2 just contains the center "blob", and not the whole image

```python
#python 3.7
import cmath
import math
import numpy as np
import matplotlib.pyplot as plt
from pynufft import NUFFT_cpu

def expectedIFT(img, X, u, v):
    N = img.shape[0] // 2
    for x in range(-N, N):
        for y in range(-N, N):
            img[x-N, y-N] = img[x-N, y-N] + X * cmath.exp(2j * math.pi * (u*x + v*y))
           
u0 = 0.05
v0 = 0.013
u1 = 0.0018
v1 = 0.046

img = np.zeros((32, 32), dtype=np.complex128)
expectedIFT(img, 3, u0, v0)
expectedIFT(img, 2.5, u1, v1)
plt.imshow(np.real(img))
print(np.max(np.real(img)))
#prints expected value 5.5


NufftObj = NUFFT_cpu()
Nd = (32, 32)  # image size
Kd = (64, 64)  # k-space size
Jd = (2, 2)  # interpolation size
om = [
      [u0, v0],
      [u1,v1]]

NufftObj.plan(np.asarray(om), Nd, Kd, Jd)
img2 = NufftObj.adjoint([3, 2.5])
plt.imshow(np.real(img2))
print(np.max(np.real(img2)))
#prints value << 1
```

**Comment by jyhmiinlin** [comment]
Thank you for the question. In short,  
1. The forward operation remains unscaled while the adjoint operation is scaled in all dimensions. This is based on Numpy's FFT convention: "The default normalization has the direct transforms unscaled and the inverse transforms are scaled by 1/n". (https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.fft.html#normalization)

2. Frequency is normalized to the range of [-pi, pi]. In your case: (numpy.arange(0, N)*2.0 - N)*numpy.pi/N 

I agree that the documentation could include a basic check comparing NUFFT and FFT. There is a work by Benoit and would like to find the link later.

**Comment by soumickmj** [comment]
I'm trying to reconstruct raw data acquired by Simens Skyra scanner using Star VIBE sequence. I'm not using forward as the data is already in radial k-Space. I'm just using adjoint on the data to get the image. The resultant image looks OK, but the values are too small. 

Min: (-2.8952071e-08+4.702143e-10j)
Max: (2.9728515e-08-2.7196707e-09j)

If I take np.abs of the resultant image, then:-
Min: 6.160515e-12
Max: 3.502556e-08

Is there any way to stop the normalization process or to normalize them in some other way?

Thanks.

**Comment by jyhmiinlin** [comment]
Thanks for the question. You may multiply the adjoint image by the "product of all Kd values" or the square root of the products. The choice depends on how you would like to normalize the data. 

For example, sqrt (512 x 512 x 16): if the oversampled x-y grid is 512 x 512. 16 may be the number of stacks or it could be 32 (twice the number)

Please let me know if this works for you.

**Comment by soumickmj** [comment]
Thanks for the response.
For my case, Kd is (576,576).
So, now I'm doing iamge0=image*np.prod(NufftObj.Kd)
where image is the adjoint image.
What is this 16 you mentioned? I mean the number of stacks? What do you mean by that?
Doing so the values are not as small as before, but still, they are quite small the original expected values
