### ISSUE TITLE
NUFFT_hsa giving TypeError

### ISSUE THREAD

**Issue by ghost** [jyhmiinlin/pynufft#15]
While running the given 2D example, it gives TypeError when it encounters image0 = NufftObj.solve(y, solver='cg',maxiter=50)
No other info is provided, just it says type error.
The same code works perfectly when using NUFFT_cpu

**Comment by jyhmiinlin** [comment]
Would you post the code which causes the problem? 

Without the detail I can only guess y is a numpy.array. To use NUFFT_hsa, the data y must be a gpu array: 
#Move y to gy:
gy = NufftObj.thr.to_device(y.astype(numpy.complex64))

An example for NUFFT_hsa.solve is in the file https://github.com/jyhmiinlin/pynufft/blob/master/tests/test_init.py, line 134.

**Comment by soumickmj** [comment]
import numpy 
import scipy.misc
import matplotlib.pyplot 
from pynufft import NUFFT_hsa, NUFFT_cpu

import pkg_resources
DATA_PATH = pkg_resources.resource_filename('pynufft', './src/data/')
om = numpy.load(DATA_PATH+'om2D.npz')['arr_0']
print(om)
print('setting non-uniform coordinates...')
matplotlib.pyplot.plot(om[::10,0],om[::10,1],'o')
matplotlib.pyplot.title('non-uniform coordinates')
matplotlib.pyplot.xlabel('axis 0')
matplotlib.pyplot.ylabel('axis 1')
matplotlib.pyplot.show()

NufftObj = NUFFT_cpu()

Nd = (256, 256)  # image size
print('setting image dimension Nd...', Nd)
Kd = (512, 512)  # k-space size
print('setting spectrum dimension Kd...', Kd)
Jd = (6, 6)  # interpolation size
print('setting interpolation size Jd...', Jd)

NufftObj.plan(om, Nd, Kd, Jd)

image = scipy.misc.ascent()
image = scipy.misc.imresize(image, (256,256))
image=image/numpy.max(image[...])

print('loading image...')

matplotlib.pyplot.imshow(image.real, cmap=matplotlib.cm.gray)
matplotlib.pyplot.show()


y = NufftObj.forward(image)
print('setting non-uniform data')
print('y is an (M,) list',type(y), y.shape)


NufftObj = NUFFT_hsa()

Nd = (256, 256)  # image size
print('setting image dimension Nd...', Nd)
Kd = (512, 512)  # k-space size
print('setting spectrum dimension Kd...', Kd)
Jd = (6, 6)  # interpolation size
print('setting interpolation size Jd...', Jd)

NufftObj.plan(om, Nd, Kd, Jd)

gy = NufftObj.thr.to_device(y.astype(numpy.complex64))

matplotlib.pyplot.subplot(2,2,1)
image0 = NufftObj.solve(gy, solver='cg',maxiter=50)
matplotlib.pyplot.title('Restored image (cg)')
matplotlib.pyplot.imshow(image0.real, cmap=matplotlib.cm.gray, norm=matplotlib.colors.Normalize(vmin=0.0, vmax=1))


matplotlib.pyplot.subplot(2,2,2)
image2 = NufftObj.adjoint(gy )
matplotlib.pyplot.imshow(image2.real, cmap=matplotlib.cm.gray, norm=matplotlib.colors.Normalize(vmin=0.0, vmax=5))
matplotlib.pyplot.title('Adjoint transform')


matplotlib.pyplot.subplot(2,2,3)
image3 = NufftObj.solve(gy, solver='L1TVOLS',maxiter=50,rho=0.1)
matplotlib.pyplot.title('L1TV OLS')
matplotlib.pyplot.imshow(image3.real, cmap=matplotlib.cm.gray, norm=matplotlib.colors.Normalize(vmin=0.0, vmax=1))

matplotlib.pyplot.subplot(2,2,4)
image4 = NufftObj.solve(gy, solver='L1TVLAD',maxiter=50,rho=0.1)
matplotlib.pyplot.title('L1TV LAD')
matplotlib.pyplot.imshow(image4.real, cmap=matplotlib.cm.gray, norm=matplotlib.colors.Normalize(vmin=0.0, vmax=1))
matplotlib.pyplot.show()


shifted_kspectrum = numpy.fft.fftshift(numpy.fft.fftn(numpy.fft.fftshift(image0)))print('Showing the shifted k-space spectrum')

matplotlib.pyplot.imshow( shifted_kspectrum.real, cmap = matplotlib.cm.gray, norm=matplotlib.colors.Normalize(vmin=-100, vmax=100))
matplotlib.pyplot.title('shifted k-space spectrum')
matplotlib.pyplot.show()

**Comment by soumickmj** [comment]
After adding #Move y to gy:
gy = NufftObj.thr.to_device(y.astype(numpy.complex64))

I get the following error:-
AttributeError: 'NUFFT_hsa' object has no attribute 'thr'

**Comment by soumickmj** [comment]
While running https://github.com/jyhmiinlin/pynufft/blob/master/tests/test_init.py I got the same Attribute Error

**Comment by jyhmiinlin** [comment]
It seems the NUFFT_hsa is missing the GPU context. There are a couple of possible reasons. For gpu computing there are some requirements which must be met:

1. Please check the pycuda, pyopencl, reikna have been installed in your Python distribution. The opencl and cuda libraries must be available on the system. Recent CUDA versions should be OK. However, installing OpenCL is very tricky, and clinfo should give you some information about the available opencl.
2. If the hardware/software is ready:
NufftObj = NUFFT_hsa()
NufftObj.plan(om, Nd, Kd, Jd)
NufftObj.offload(API = 'ocl',   platform_number = 0 , device_number = 0)
or 
NufftObj.offload(API = 'cuda',   platform_number = 0 , device_number = 0)

3. Now you may send y to GPU:
gy = NufftObj.thr.to_device(y.astype(numpy.complex64))
Then good luck.

**Comment by ghost** [comment]
I'm using CUDA, not opencl.
I'm now getting the following error:-
pycuda.driver.CompileError: nvcc compilation of C:\Users\soumi\AppData\Local\Temp\tmponfupol6\kernel.cu failed
[command: nvcc --cubin -arch sm_61 -m64 -Ic:\users\soumi\appdata\local\conda\conda\envs\testenv\lib\site-packages\pycuda\cuda kernel.cu]
[stdout:
kernel.cu
]

But when I run the tests test_cumath.py, python test_driver.py, python test_gpuarray.py of the pycuda, all executes successfully, and returns 'passed' for all.

I'm using Python 3.7.1 (Anaconda) in Windows 10 x64

**Comment by jyhmiinlin** [comment]
To be honest, I haven't had a windows 10 machine. So the only suggestion is to install Linux (e.g. ubuntu 16.04, 18.04). 

Another thing to check is that the Python package "reikna" should be installed. I installed the latest github version. Please run the following diagnostic check for reikna (from Anaconda's Python):

#######################
import reikna.cluda as cluda
api = cluda.cuda_api()
dev = api.get_platforms()[0].get_devices()[0]
thr = api.Thread(dev)
import numpy
shape = (384,384, 29, 20)
gb = thr.array(shape, dtype =numpy.complex64)
ga = thr.array(shape, dtype =numpy.complex64).fill(1.0)
thr.copy_array(ga, gb)
print('gb shape=', gb.shape)
print('ga shape=', ga.shape)
print('done')
###################################

The correct result will be

gb shape= (384, 384, 29, 20)
ga shape= (384, 384, 29, 20)
done

This will check whether the basic environment is correct. Otherwise, I will try windows 10 and test it, which will take a while.

**Comment by jyhmiinlin** [comment]
I welcome you to contribute a story of successful installation on Windows 10 if you (or anyone) have figured out how to do it. Theoretically, the GPU backends should be working, but I don't have enough experiences and resources to get a Windows 10 machine for testing.

**Comment by jyhmiinlin** [comment]
I tried to replicate the error and search related web pages. Unfortunately, there are rare stories about PyCUDA, CUDA 10, Windows 10. 

The closest information is https://stackoverflow.com/questions/44463272/pycuda-compileerror-with-anaconda-on-windows but may not be helpful. It turns out nvcc cannot correctly compile the .cu code, which means nvcc cannot correctly use the compiler. The error is related to Microsoft Visual Studio and CUDA. Not specific to PyNUFFT. 

I am closing this post for now. Please ensure a working system can compile CUDA source.

**Comment by jyhmiinlin** [comment]
Thanks. I took some time to solve the issue. Just a note that Windows 10 is included in the current version at the GitHub.  

I open a new issue with the title Windows 10 installation https://github.com/jyhmiinlin/pynufft/issues/16

OpenCL requires some environment variables but I made it work as well.

**Comment by soumickmj** [comment]
I'm encountering similar problem in my linux servers as well.
I'm using ubuntu (16.04.6 LTS + Cuda 10.0.130) and (16.04.5 LTS + Cuda 9.2.148)
I really don't option to change cuda versions in either server.
PuCUDA and Reikna are installed.

When I'm calling forward, I get the following error:-
'NUFFT_hsa' object has no attribute 'thr'

If I call this before sending image to forward,
image = NufftObj.thr.to_device(image)
then I get the same error in that line.

If I include NufftObj.offload(API = 'cuda', platform_number = 0 , device_number = 0)
after plan, 
then I get a C++ error
ERROR:root:Failed to compile:

then 486 lines of C++ code. 

Can you please help me out? What could be possible reason?

**Comment by jyhmiinlin** [comment]
There are many possible causes. The installed PyCUDA cannot compile the source and here I can only give some hints. Please refer to the PyCUDA installation.

1. First, please make sure you can compile the source code of PyCUDA (https://documen.tician.de/pycuda/)

2. The PyNUFFT may be too old. Uninstall the previous version and Install the lastest pynufft from the github. 

2. Alternatively, try PyopenCL and tell me if this works. 

Good luck.
