### ISSUE TITLE
Quick question about recovering kspace data

### ISSUE THREAD

**Issue by zwep** [jyhmiinlin/pynufft#17]
After reading your long comment on the following old post

https://github.com/jyhmiinlin/pynufft/issues/1

I see that there you talk about y2k_DC functions... hence which performs density compensation. I don't see these anymore in the current version.
Does this mean that Density Compensation is now performed by default?

Another question.. in my case.. the following procedure gives a very blurry image. It looks like the center of k-space is totally missing.

NufftObj = pynufft.NUFFT_cpu()
NufftObj.plan(...)
y = NufftObj.forward(x)
k = NufftObj.y2k(y)
y0 = NufftObj.k2y(y)
x0 = NufftObj.solve(y0, solver='cg')

Is the procedure correct? If so, then it is probably due to my trajectories that I have chosen.

**Comment by jyhmiinlin** [comment]
There is no default choice of solver. 'dc' is the density compensation using the precomputed weighting function. 'cg' is least square fitting. 

In your case, y2k() and k2y() may not be necessary. forward() has already generated the non-uniform k-space data. The additional y2k() and k2y() convolve the trajectory for the second time. 

I guess the correct code may look like:

NufftObj = pynufft.NUFFT_cpu()
NufftObj.plan(...)
y0 = NufftObj.forward(x)
x0 = NufftObj.solve(y0, solver='cg')

Please let me know if this works for you.

**Comment by zwep** [comment]
Hmm, okay thanks for the info! 

But Im not quite there yet. Let's say Im doing radial sampling, and have n_spokes as the number of spokes from which I sample the kspace data. These n_spokes have a length of n_oversampled.
Where n_oversampled is larger than the image size, and n_spokes can be chosen in some clever manner...

If in this case I would do

y = NufftObj.forward(x)

then this variable will be a (n_spokes * n_oversampled, ) vector. If I want this into the form (n_spokes, n_oversampled), can I then just reshape this vector?

Because that is what Im doing now.. but when I look at the max/mean values of the obtained complex data, it does not seemed to be scaled properly. Like, I get way larger values than when I would do normal fft in a cartesian setting...

**Comment by zwep** [comment]
Sorry, I think I can formulate my question better..

what I want is the regridded kspace from the pynufft object.

**Comment by jyhmiinlin** [comment]
Scaling is discussed in #14 

All the points of n_oversampled and n_spokes are mapped to the k-space, which is normalized to [-pi, pi] centered at 0. 

Close it for now. Would reopen if needed.
