### ISSUE TITLE
2D Reconstruction Protocol 

### ISSUE THREAD

**Issue by TRDim** [jyhmiinlin/pynufft#22]
Hey Jyh, 

I tried to go through your examples but still the whole process to reconstruct some non-cartesian data is still unclear. 
I want to use my own k-space data, scanned in a 2D radial fashion (512 spokes, 512 samples) 
I use as an input a **y-(complex128)** reshaped from (512,512) -> **(262144,)** as well as the sampling locations in k-space in an ****om**-(float64) (262144,2)**  
 (Coordinates:  1st column - x  , 2nd column -y). 
The rest of the  Nd, Kd, Jd, are used as in the example. 

Could you please suggest me the needed steps in case that the above reconstruction is possible with pyNUFFT? 
Thank you in advance

**Comment by jyhmiinlin** [comment]
Please contact PyNUFFT services at pynufft@gmail.com.
