### ISSUE TITLE
NUFFT_cpu does not work on the system without CUDA

### ISSUE THREAD

**Issue by Sergey-Anfinogentov** [jyhmiinlin/pynufft#25]
Dear Jyh-Miin Lin,

First of all, I would like to thank you for developing PyNUFFT. It appeared to bevery usefull for my research work.

I found that in the latest version of PyNUFFT `NUFFT_cpu` does not work without CUDA.
An attempt to import NUFFT_cpu on a system without CUDA libraries `from pynufft import NUFFT_cpu` causes the following error message:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-74d31676ef6d> in <module>()
----> 1 from pynufft import NUFFT_cpu

1 frames
/usr/local/lib/python3.6/dist-packages/pynufft/linalg/nudft_cupy.py in <module>()
      6 
      7 from __future__ import absolute_import
----> 8 import cupy
      9 import numpy
     10 import scipy.sparse

ModuleNotFoundError: No module named 'cupy'
```
You may also look at the [Google Colaboratory notebook](https://colab.research.google.com/drive/1lMnphS3zA8FOBRM6bGY8a704yq2_soxX?usp=sharing) where the problem is reproduced.
My attempt to manually install the `cupy` package failed since I don't have Nvidia GPU and CUDA drivers in my system.

I would expect `NUFFT_cpu` to work correctly without any GPU specific libraries as it was in previous versions.

Best Regards,
Sergey

**Comment by jyhmiinlin** [comment]
Indeed. Please use the NUFFT class. The NUFFT_cpu and NUFFT_hsa have been deprecated.


>>> from pynufft import NUFFT
>>> import numpy
>>> A = NUFFT()
>>> om = numpy.random.randn(10,2)
>>> Nd = (64,64)
>>> Kd = (128,128)
>>> Jd = (6,6)
>>> A.plan(om, Nd, Kd, Jd)
0
>>> x=numpy.random.randn(*Nd)
>>> y = A.forward(x)

Sorry for the change. The document will be changed accordingly.

**Comment by Sergey-Anfinogentov** [comment]
Thank you for your quick reply and advice.
