### ISSUE TITLE
What is om?

### ISSUE THREAD

**Issue by kaanaksit** [jyhmiinlin/pynufft#26]
Can you please explain to me what is `om` that is used during:

```python
    NufftObj.plan(
                  om, 
                  image.shape,
                  (image.shape[0]*2,image.shape[1]*2),
                  (6,6)
                 )
```

This is a great mystery for me. Please help me understand it.

**Comment by jyhmiinlin** [comment]
Please read the tutorial http://jyhmiinlin.github.io/pynufft/tutor/more2D.html. Close it.
