### ISSUE TITLE
Mem Allocation Error

### ISSUE THREAD

**Issue by Babji-Gandi** [jyhmiinlin/pynufft#27]
Hi,
I recently started working on pynufft and I am Calculating cpu and gpurun  times for Forward opeartion.I gave same inputs for cpu and gpu and i got few errors for gpu combinations where those combinations were working on cpu.I am attaching the documents from the one of the errors I got.
I got same error for few more combinations only for gpu.Please try to help me in solving this issue.
![nd1024 kd512 jd6 error](https://user-images.githubusercontent.com/72522302/104598070-6aa10800-5676-11eb-9c9f-f272e5ac222b.png)

I performed this operation on Google colab gpu and as well as another gpu.

Thank you.

**Comment by jyhmiinlin** [comment]
No experience with Colab so I cannot recommend Colab to users. I searched and found Colab GPU is more stable for subscribed users? But you are welcome to write a report if you make it work.

**Comment by Babji-Gandi** [comment]
Hi,
Do you think that error is because of I am using google colab gpu?If yes,Please suggest me which gpu to use.

Thanking You,
Babji Gandi.

**Comment by jyhmiinlin** [comment]
Please see the hardware and software requirements, and installation procedure http://jyhmiinlin.github.io/pynufft/installation/init.html#system-requirements. 

If you need further support, Please contact pynufft@gmail.com.
