### ISSUE TITLE
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zwep** [jyhmiinlin/pynufft#28]
Hi,

I just re-installed version 
`pynufft                2020.2.7`

but upon importing pynufft I get the following import error

ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

do you know what to do?

**Comment by jyhmiinlin** [comment]
Didn't experience the issue. It is the OpenBlas installation problem. Google shows some related issues: https://stackoverflow.com/questions/36893382/scipy-installation-issue-getting-importerror-libopenblas-so-0-cannot-open-sha

**Comment by zwep** [comment]
Sorry for the inconvenience, it was a fault on my end with `scipy`
