### ISSUE TITLE
Point spread Function

### ISSUE THREAD

**Issue by Babji-Gandi** [jyhmiinlin/pynufft#30]
I am reconstructing 2D MR Image and can someone help me out in finding point spread function in an image?
It would be a great help if someone can answer.

Thanking you.

**Comment by jyhmiinlin** [comment]
Please fill the application form https://docs.google.com/forms/d/1J0gZ28Y37sk_ljrwmLJJxdyuAyRAH0EGIFJlaWsDN3s/edit . Someone will get in touch with you. Many thanks.
