### ISSUE TITLE
except: pass statement in helper

### ISSUE THREAD

**Issue by bwheelz36** [jyhmiinlin/pynufft#31]
Hey :-)
Just a minor thing. in helper, line 1515, there is an except: pass statement. 

From my perspective except: raise would probably be better, or except ErrorType: Message...
This just took me a while to fix an error that the raise message revealed was actually pretty simple (and completely my fault :-P)

**Comment by jyhmiinlin** [comment]
Keep this issue open until solving it. If there is a PR I would like to accept it.

**Comment by jyhmiinlin** [comment]
Raising an error can stop the program. I make it to print some texts and to give a clue in a non-block way. Now it will print('No OpenCL device found. Check your pyopencl installation.') or print('No CUDA device found. Check your pycuda installation.').

**Comment by bwheelz36** [comment]
thanks :-)
