### ISSUE TITLE
L1TVOLS solver does not work for spiral and radial trajectories

### ISSUE THREAD

**Issue by Mmj94** [jyhmiinlin/pynufft#32]
Hello,

I've been investigating the different solvers in your package. They all work when using the propeller trajectory provided in the tutorial, however, the L1TV-OLS does not work for custom spiral and radial trajectories.

Seems like the bug is related to the density compensation calculation. I modified a line of code in `solve_cpu.py`, specifically line :
`uker = mu*numpy.abs(nufft.xx2k(nufft.adjoint(_pipe_density(nufft, maxiter)*y))) # MMJ added`
instead of
`uker1 = mu*_create_kspace_sampling_density(nufft)`

This line modification seems to work better for the spiral and radial trajectories, although with some exceptions.

**Comment by jyhmiinlin** [comment]
Interesting. I don't know why they are suitable for different problems?

**Comment by jyhmiinlin** [comment]
If no further discussion the issue is closed. Currently, the NUFFT forward and adjoint operators are supported. Users are encouraged to develop their own solvers.
