### ISSUE TITLE
Docs missing definition or clarity?

### ISSUE THREAD

**Issue by cottrell** [jyhmiinlin/pynufft#33]
I'm trying to understand the simplest use case of 1d fft of (x, y) -> f (and implied k I assume) where x.shape == y.shape

I noticed in the docs here the Nd, Kd, Jd, M are not defined:

   http://jyhmiinlin.github.io/pynufft/tutor/basic_use.html

I am probably missing something obvious, but it seems like the docs are either unclear or wrong? Where does *x* appear in the setup or the tutorial 1d?

**Comment by cottrell** [comment]
I suspect this is the intended usage: 

```
In [91]: from pynufft import NUFFT

In [92]: m = 1000

In [93]: x = np.random.randn(m)

In [94]: y = np.random.randn(m)

In [95]: Nd = (256,)
    ...: Kd = (512,)
    ...: Jd = (6,)

In [96]: nu.plan(x[:, None], Nd, Kd, Jd)
Out[96]: 0

In [97]: f = nu.adjoint(y)

In [98]: f.shape
Out[98]: (256,)

In [99]: y_ = nu.forward(f)

In [100]: y_.shape
Out[100]: (1000,)
```

**Comment by jyhmiinlin** [comment]
Ok. There was a vague definition in Figure 1.
http://jyhmiinlin.github.io/pynufft/overview/Nd_NUFFT.html
