### ISSUE TITLE
scipy.linalg.pinv2 is deprecated

### ISSUE THREAD

**Issue by patquem** [jyhmiinlin/pynufft#35]
Hello,

Could you please address the following change:

```
pynufft\src\_helper\helper.py:1055: DeprecationWarning: scipy.linalg.pinv2 is deprecated since SciPy 1.7.0, use scipy.linalg.pinv instead
  B = scipy.linalg.pinv2(A)
```

Thanks,
Patrick

**Comment by jyhmiinlin** [comment]
Thanks, I will track this issue. So far my scipy 1.8.1 didn't show the warning but I am aware that pinv2 is deprecated.

**Comment by gschramm** [comment]
I can confirm that tests.init(0) fails with scipy 1.9.
In general, I think it would be better to be more specific with compatible package versions in the setup.py.

For it seems that some required packages are completely missing there (e.g. I had to manually install "reikna")

**Comment by jyhmiinlin** [comment]
Thanks for confirming the issue. pinv2 is replaced by pinv since 2022.2.3. 

I am considering rearranging the pycuda / pyopencl classes and the version information because GPU programming has changed over the past 4 years. However, this will belong to a new issue.
