### ISSUE TITLE
Can the torch implementation take the non-cartesian coordinates as a tensor?

### ISSUE THREAD

**Issue by apt-get-nat** [jyhmiinlin/pynufft#36]
I'm trying to pass derivatives through my fourier layer with respect to the node locations. However, I can only get the package to work with om defined as a numpy array -- I think this makes the gradient calculation impossible. Is it possible to run the package with om as a torch object?

**Comment by apt-get-nat** [comment]
It seems that you cannot pass a tensor through as written, but it required minimal changes to alter some numpy operations on om to torch.Tensor operations. Hopefully that is sufficient.

**Comment by jyhmiinlin** [comment]
In the following command, the om could be changed from NumPy array to the torch tensor.

A2= NUFFT_torch()
A2.plan(**om**, Nd, Kd, Jd)

It is possible. Just to make sure if this is what you suggest?

**Comment by apt-get-nat** [comment]
Yes, that is what I'm suggesting. I had to change about half a dozen numpy calls in helper.py to pass a tensor through as om, but after those are changed, it all seems to work. Do you think there's anything in the algorithm that won't be differentiable with respect to om?

**Comment by jyhmiinlin** [comment]
om is a design parameter for the NUFFT class. After the planning stage, om will not be used. 

NUFFT_torch uses a sparse tensor internally. The sparse tensor has self.torch_sp and self.torch_spH internally. Not sure if the sparse tensor is differentiable or a better way of doing this?
