### ISSUE TITLE
scipy.fftfreq equivalent helper function?

### ISSUE THREAD

**Issue by k-a-mendoza** [jyhmiinlin/pynufft#42]
Love pyNUFFT. Turns out its quite useful for analyzing the outputs of 3D FEM simulations.

However, I'm running into some trouble trying to compare the 3D power spectrum outputs between different model discretizations. I suspect this could be solved via a scipy.fftfreq equivalent, but I'm not sure how to do the math for it. I suppose in my case this would correspond to something like spatial frequency per axis? does pyNUFFT have an implementation for this?

**Comment by jyhmiinlin** [comment]
No, currently it offers complex-valued output. I am not familiar with scipy. fftfreq. Any suggestions?

**Comment by k-a-mendoza** [comment]
I guess I'm not sure how to mathematically calculate the frequency bin centers with a NUFFT of type I. I *suspect* it has something to do with the min sampling freq and max freq. Here's the link to the scipy implementation https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fftfreq.html#scipy.fft.fftfreq
