### ISSUE TITLE
Support for large data sizes?

### ISSUE THREAD

**Issue by JeffFessler** [jyhmiinlin/pynufft#45]
It looks like this NUFFT codes uses a sparse matrix for the interpolation coefficients, right?

https://github.com/jyhmiinlin/pynufft/blob/8e62b56952fd5d3049869dacf10bb73d0749c0f6/linalg/nufft_cpu.py#L339

Typically such a sparse matrix has a size proportional to the number of k-space samples.  Has anyone used this code for 3D k-space sampling with lots of samples?  One of my group members ran out of memory in that situation.

Some other NUFFT frameworks have a "table" option that requires a fixed amount of memory, independent of the number of k-space samples, e.g., https://github.com/mmuckley/torchkbnufft

Is there such an option here?  I couldn't find it.

**Comment by jyhmiinlin** [comment]
3D memory size is approximately ∝ J1*J2*J3*M. It is possible to lower the memory by OpenCL on Intel CPU(Memory approximately ∝(J1+J2+J3)*M). 


I don't have a good answer to the table method now. I thought CPU could have lots of memory and I didn't pay much attention to it.

**Comment by JeffFessler** [comment]
Ok, thanks for the reply.  I was unaware that OpenCL could reduce it to sum(J) instead of prod(J).  That's intriguing.  Is there a reference to that online somewhere with more details?  Thanks!

**Comment by jyhmiinlin** [comment]
Hi, 

http://dx.doi.org/10.1109/ICECIE52348.2021.9664682

**Comment by jyhmiinlin** [comment]
Please fill the following form 

https://docs.google.com/forms/d/1J0gZ28Y37sk_ljrwmLJJxdyuAyRAH0EGIFJlaWsDN3s/edit

**Comment by JeffFessler** [comment]
Thanks for the help and the URL!
