### ISSUE TITLE
Where are the Fourier coefficients?

### ISSUE THREAD

**Issue by wkirgsn** [jyhmiinlin/pynufft#46]
I am going over the docs over and over again but cannot make out where I would find the Fourier coefficients.
I am looking for the Fourier coefficients on equidistant frequencies given nonequidistant samples in the time/space domain.

**Comment by jyhmiinlin** [comment]
The current package has no plan to implement a simple API for calculating the Fourier coefficients on equispaced frequencies from non-uniform time/space. The adjoint transform from the irregularly spaced might be calculated by adjoint() method, using the idea in https://adamsiembida.com/how-to-compute-the-ifft-using-only-the-forward-fft/  . However, the "reconstruction" of the inverse problem could be challenging.

**Comment by wkirgsn** [comment]
thank you for clarifying
