### ISSUE TITLE
Does this work on non-uniformly sampled time series? 

### ISSUE THREAD

**Issue by axelwang** [jyhmiinlin/pynufft#47]
If my understanding is correct, this package takes **uniformaly** sampled time-domain data and then FFT it to a non-uniformaly sampled frequency domain, which allows you to have different resolutions in frequency.

However, I don't think this package can deal with time series that are non-uniformly sampled? 

I came here because I am working on a problem where time series are sampled at very different scales (more than 10 orders of magnitude!) so that interpolating to a uniform time step size is impossible. I'd like to take a Fourier transform of that time series but I guess this package won't help me?

**Comment by jyhmiinlin** [comment]
> Axel (Shiqi) Wang ***@***.***> 於 2023年12月24日 上午11:11 寫道：
> 
> 
> If my understanding is correct, this package takes uniformaly sampled time-domain data and then FFT it to a non-uniformaly sampled frequency domain, which allows you to have different resolutions in frequency.
> 
Yes, it is.

> However, I don't think this package can deal with time series that are non-uniformly sampled?
> 

It is hard to say it is impossible to deal with the package. However, it requires a more complicated algorithm than direct transform. 

> I came here because I am working on a problem where time series are sampled at very different scales (more than 10 orders of magnitude!) so that interpolating to a uniform time scale is impossible. I'd like to take a Fourier transform of that time series but I guess this package won't help me?
> 
It is an interesting question. I don’t have a simple answer using the current package.

**Comment by evileleven** [comment]
maybe try nfft package (https://github.com/jakevdp/nfft) transforming nonuniform time data to frequency domain
