### ISSUE TITLE
irregularly sampled data to regular frequency samples

### ISSUE THREAD

**Issue by bhatiaharsh** [jyhmiinlin/pynufft#7]
As far as I can understand, pynufft transforms regularly-sampled time-signal to irregularly-sampled frequency component. Is it possible to do the reverse: transform irregularly-sampled time-signal to regularly sampled frequency components?  These features are available in the nfft library, and I was wondering if there is a plan to include them in pynufft.

**Comment by jyhmiinlin** [comment]
Thank you. Irregular to regular mapping is the inverse of forward nufft transform. 

In the current forward nufft, 

y=**A**x

**A** is a mapping from the regular grid (x) to irregular samples (y). 

Then the inverse is to find x, if y and **A** are provided.

For completeness, yes, several existing solvers (e.g. conjugate gradient method in scipy.sparse), as well as examples, will be integrated into pynufft.

**Comment by jyhmiinlin** [comment]
Hi,

Please see the updated PyNUFFT v0.3.3. 

The tutorial (http://jyhmiinlin.github.io/pynufft/quickstart/more2D.html) provides a 2D example about how to use the solve():

...
y = NufftObj.forward(image) _# this performs the forward NUFFT_
image0 = NufftObj.solve(y, solver='cg',maxiter=50) _# solve the NUFFT_
shifted_kspectrum = numpy.fft.fftshift(numpy.fft.fftn(numpy.fft.fftshift(image0))) _# this finds the spectrum_
..

Regards

J

**Comment by bhatiaharsh** [comment]
Thank you. I will take a look at this sometime in the coming month.
