### ISSUE TITLE
error in import

### ISSUE THREAD

**Issue by itaysason** [jyhmiinlin/pynufft#8]
when i try to import pynufft.tests i get the following error:

> import pynufft.tests as tests
> Traceback (most recent call last):
>   File "<ipython-input-5-b9d1545f98eb>", line 1, in <module>
>     import pynufft.tests as tests
>   File "/home/itays/pycharm-2017.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
>     module = self._system_import(name, *args, **kwargs)
>   File "/home/itays/pycharm-2017.3/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 102, in patched_import
>     return original_import(name, *args, **kwargs)
>   File "/home/itays/.conda/envs/pswf_env/lib/python2.7/site-packages/pynufft/tests/__init__.py", line 3, in <module>
>     from .example_2D import example_2D
>   File "/home/itays/pycharm-2017.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
>     module = self._system_import(name, *args, **kwargs)
>   File "/home/itays/pycharm-2017.3/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 102, in patched_import
>     return original_import(name, *args, **kwargs)
>   File "/home/itays/.conda/envs/pswf_env/lib/python2.7/site-packages/pynufft/tests/example_2D.py", line 4, in <module>
>     from ..pynufft import NUFFT_cpu, NUFFT_hsa
>   File "/home/itays/pycharm-2017.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
>     module = self._system_import(name, *args, **kwargs)
>   File "/home/itays/pycharm-2017.3/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 102, in patched_import
>     return original_import(name, *args, **kwargs)
>   File "/home/itays/.conda/envs/pswf_env/lib/python2.7/site-packages/pynufft/pynufft.py", line 1, in <module>
>     from .src._transform.transform_cpu import NUFFT as NUFFT_cpu
>   File "/home/itays/pycharm-2017.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
>     module = self._system_import(name, *args, **kwargs)
>   File "/home/itays/pycharm-2017.3/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 102, in patched_import
>     return original_import(name, *args, **kwargs)
> ImportError: No module named src._transform.transform_cpu

also, in the user manual, can you specify the formula you are using in the nufft?

**Comment by jyhmiinlin** [comment]
Thanks, 

".conda/envs/pswf_env/lib/python2.7/site-packages/pynufft/tests/init.py"
Python2 is currently unsupported. Please use Python3 at this moment and in the future. However, I will keep this bug open and try to fix the backward compatibility for python2.

The formula I used is the nufft of min-max interpolator (https://web.eecs.umich.edu/~fessler/papers/files/jour/03/pre/tsp,nufft.pdf). The user manual will be updated in the near future.

**Comment by itaysason** [comment]
thank you!
