### ISSUE TITLE
Uniform→nonuniform?

### ISSUE THREAD

**Issue by fasiha** [jyhmiinlin/pynufft#9]
The [1D example](http://jyhmiinlin.github.io/pynufft/quickstart/example.html) takes a uniformly-sampled-in-time signal and calculates its non-uniform DFT. Is there a straightforward way to take a non-uniformly-sampled-in-time signal and calculate its uniform DFT?

**Comment by jyhmiinlin** [comment]
As far as I know, it requires iterative solvers.

**Comment by fasiha** [comment]
Understood, thanks!
